In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Robin\OneDrive\Documents\Flight_Delay_Analytics\data\flights_sample_3m.csv")
print("Dataset Loaded Successfully")
print("Shape:", df.shape)
df.head()

Dataset Loaded Successfully
Shape: (3000000, 32)

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [23]:
# ===============================
# WEEK 1 -  SCHEMA ANALYSIS
# ===============================

print("Column Data Types:")
print(df.dtypes)

print("\nColumn List:")
print(df.columns.tolist())

# Separate columns by type
categorical_cols = df.select_dtypes(include='object').columns
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

print("\nCategorical Columns:", categorical_cols)
print("\nNumeric Columns:", numeric_cols)

Column Data Types:
FL_DATE                     object
AIRLINE                     object
AIRLINE_DOT                 object
AIRLINE_CODE                object
DOT_CODE                     int64
FL_NUMBER                    int64
ORIGIN                      object
ORIGIN_CITY                 object
DEST                        object
DEST_CITY                   object
CRS_DEP_TIME                 int64
DEP_TIME                   float64
DEP_DELAY                  float64
TAXI_OUT                   float64
WHEELS_OFF                 float64
WHEELS_ON                  float64
TAXI_IN                    float64
CRS_ARR_TIME                 int64
ARR_TIME                   float64
ARR_DELAY                  float64
CANCELLED                  float64
CANCELLATION_CODE           object
DIVERTED                   float64
CRS_ELAPSED_TIME           float64
ELAPSED_TIME               float64
AIR_TIME                   float64
DISTANCE                   float64
DELAY_DUE_CARRIER          float64
DELAY_DUE_WEATHER          float64
DELAY_DUE_NAS              float64
DELAY_DUE_SECURITY         float64
DELAY_DUE_LATE_AIRCRAFT    float64
dtype: object

Column List:
['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE', 'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER', 'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY', 'DELAY_DUE_LATE_AIRCRAFT']

Categorical Columns: Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'ORIGIN',
       'ORIGIN_CITY', 'DEST', 'DEST_CITY', 'CANCELLATION_CODE'],
      dtype='object')

Numeric Columns: Index(['DOT_CODE', 'FL_NUMBER', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY',
       'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME',
       'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [32]:
df.describe()

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,300000.000000,300000.000000,300000.000000,292292.000000,300000.000000,292168.000000,292168.000000,292047.000000,292047.000000,300000.000000,...,300000.000000,299999.000000,291382.000000,291382.000000,300000.000000,53521.000000,53521.000000,53521.000000,53521.000000,53521.000000
mean,19976.372630,2513.921653,1327.867817,1330.649303,10.025273,16.658039,1353.234047,1463.544056,7.688304,1491.170703,...,0.002503,142.504398,136.857781,112.523011,811.146313,25.281123,4.229424,13.158685,0.141739,25.411745
std,377.316488,1748.991071,485.717135,499.342287,49.507100,9.193365,500.888860,527.387017,6.310193,511.831883,...,0.049971,71.844714,71.981883,70.059922,590.040227,72.373268,33.590647,33.970947,2.821631,55.600368
min,19393.000000,1.000000,1.000000,1.000000,-62.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,18.000000,15.000000,8.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19790.000000,1048.000000,915.000000,917.000000,-6.000000,11.000000,932.000000,1050.000000,4.000000,1109.000000,...,0.000000,90.000000,84.000000,61.000000,379.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19930.000000,2158.000000,1320.000000,1323.000000,-2.000000,14.000000,1336.000000,1502.000000,6.000000,1518.000000,...,0.000000,125.000000,120.000000,95.000000,655.000000,4.000000,0.000000,0.000000,0.000000,0.000000
75%,20368.000000,3805.000000,1730.000000,1739.000000,6.000000,19.000000,1752.000000,1909.000000,9.000000,1920.000000,...,0.000000,173.000000,168.000000,142.000000,1047.000000,23.000000,0.000000,17.000000,0.000000,29.000000
max,20452.000000,8794.000000,2359.000000,2400.000000,2895.000000,174.000000,2400.000000,2400.000000,217.000000,2359.000000,...,1.000000,695.000000,693.000000,669.000000,5095.000000,2565.000000,1326.000000,1711.000000,221.000000,1514.000000

In [ ]:

# ===============================
# WEEK 1 - Missing Values 
# ===============================

print("Missing Values:")
print(df.isnull().sum())

# Calculate Missing Percentage
null_report = df.isnull().sum()
null_percentage = (null_report / len(df)) * 100

print("Missing Percentage:")
print(null_percentage)

Missing Values:
FL_DATE                         0
AIRLINE                         0
AIRLINE_DOT                     0
AIRLINE_CODE                    0
DOT_CODE                        0
FL_NUMBER                       0
ORIGIN                          0
ORIGIN_CITY                     0
DEST                            0
DEST_CITY                       0
CRS_DEP_TIME                    0
DEP_TIME                     7708
DEP_DELAY                       0
TAXI_OUT                     7832
WHEELS_OFF                   7832
WHEELS_ON                    7953
TAXI_IN                      7953
CRS_ARR_TIME                    0
ARR_TIME                     7952
ARR_DELAY                       0
CANCELLED                       0
CANCELLATION_CODE          292133
DIVERTED                        0
CRS_ELAPSED_TIME                1
ELAPSED_TIME                 8618
AIR_TIME                     8618
DISTANCE                        0
DELAY_DUE_CARRIER          246479
DELAY_DUE_WEATHER          246479
DELAY_DUE_NAS              246479
DELAY_DUE_SECURITY         246479
DELAY_DUE_LATE_AIRCRAFT    246479
dtype: int64
Missing Percentage:
FL_DATE                     0.000000
AIRLINE                     0.000000
AIRLINE_DOT                 0.000000
AIRLINE_CODE                0.000000
DOT_CODE                    0.000000
FL_NUMBER                   0.000000
ORIGIN                      0.000000
ORIGIN_CITY                 0.000000
DEST                        0.000000
DEST_CITY                   0.000000
CRS_DEP_TIME                0.000000
DEP_TIME                    2.569333
DEP_DELAY                   0.000000
TAXI_OUT                    2.610667
WHEELS_OFF                  2.610667
WHEELS_ON                   2.651000
TAXI_IN                     2.651000
CRS_ARR_TIME                0.000000
ARR_TIME                    2.650667
ARR_DELAY                   0.000000
CANCELLED                   0.000000
CANCELLATION_CODE          97.377667
DIVERTED                    0.000000
CRS_ELAPSED_TIME            0.000333
ELAPSED_TIME                2.872667
AIR_TIME                    2.872667
DISTANCE                    0.000000
DELAY_DUE_CARRIER          82.159667
DELAY_DUE_WEATHER          82.159667
DELAY_DUE_NAS              82.159667
DELAY_DUE_SECURITY         82.159667
DELAY_DUE_LATE_AIRCRAFT    82.159667
dtype: float64

In [ ]:
import os

os.makedirs("reports", exist_ok=True)

# save file
null_report.to_csv("reports/null_analysis_report.csv", index=False)

print("Null report saved successfully.")

Null report saved successfully.

In [ ]:
# ===============================
# WEEK 1 -  SAMPLING
# ===============================

sample_df = df.sample(n=300000, random_state=42)

sample_df.to_csv("reports/sample_flights.csv", index=False)

print("Sample dataset saved successfully.")

Sample dataset saved successfully.

In [35]:
import pandas as pd

df = pd.read_csv("reports/sample_flights.csv")

In [39]:
df.fillna(0, inplace=True)

In [41]:
df['Month'] = pd.to_datetime(df['FL_DATE']).dt.month

In [42]:
df['Day'] = pd.to_datetime(df['FL_DATE']).dt.day_name()

In [43]:
df['Hour'] = df['DEP_TIME'] // 100

In [50]:
df['Route'] = df['ORIGIN'] + "-" + df['DEST']

print(df[['Month', 'Day', 'Hour', 'Route']].head())

   Month      Day  Hour    Route
0      5  Tuesday  15.0  MCO-JFK
1     11  Tuesday   7.0  FLL-DTW
2      6   Sunday  21.0  SMF-LAS
3      7   Sunday   5.0  OKC-DTW
4      3   Friday  20.0  FLL-SFO

In [47]:
df.to_csv("reportscleaned_flights.csv", index=False)

In [48]:
df = pd.read_csv("reportscleaned_flights.csv")

In [49]:
print("\nChecking Missing Values After Cleaning:")
print(df.isnull().sum())

Checking Missing Values After Cleaning:
FL_DATE                    0
AIRLINE                    0
AIRLINE_DOT                0
AIRLINE_CODE               0
DOT_CODE                   0
FL_NUMBER                  0
ORIGIN                     0
ORIGIN_CITY                0
DEST                       0
DEST_CITY                  0
CRS_DEP_TIME               0
DEP_TIME                   0
DEP_DELAY                  0
TAXI_OUT                   0
WHEELS_OFF                 0
WHEELS_ON                  0
TAXI_IN                    0
CRS_ARR_TIME               0
ARR_TIME                   0
ARR_DELAY                  0
CANCELLED                  0
CANCELLATION_CODE          0
DIVERTED                   0
CRS_ELAPSED_TIME           0
ELAPSED_TIME               0
AIR_TIME                   0
DISTANCE                   0
DELAY_DUE_CARRIER          0
DELAY_DUE_WEATHER          0
DELAY_DUE_NAS              0
DELAY_DUE_SECURITY         0
DELAY_DUE_LATE_AIRCRAFT    0
Month                      0
Day                        0
Hour                       0
Route                      0
dtype: int64